baseURL: "https://unb-mds.github.io/Projeto-P.I.T.E.R/"
languageCode: "pt-br"
title: "P.I.T.E.R"

# Configurações básicas
disableKinds: ["taxonomy", "term"]

# Configurações para GitHub Pages
relativeURLs: false

# Menus com URLs corretas para produção
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "sprint"
      name: "Sprints"
      url: "/sprint/"
      weight: 2
    - identifier: "arquitetura"
      name: "Arquitetura"
      url: "/arquitetura/"
      weight: 3

environment: production

# Performance
minify: true
enableRobotsTXT: true
enableGitInfo: true

# SEO
canonifyURLs: true

# Otimizações
build:
  writeStats: true
  
imaging:
  quality: 85
  resampleFilter: lanczos
