
baseURL: "https://unb-mds.github.io/Projeto-P.I.T.E.R/"
languageCode: "pt-br"
title: "MDS - Documentação"
theme: "mds"

# Configurações básicas
contentDir: "docs/content"
publishDir: "." # Publicar na raiz
disableKinds: ["taxonomy", "term"]
enableRobotsTXT: true

# Menus
menu:
  main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "sprint"
      name: "Sprints"
      url: "/sprint/"
      weight: 2
    - identifier: "arquitetura"
      name: "Arquitetura"
      url: "/arquitetura/"
      weight: 3
