baseURL: "https://unb-mds.github.io/Projeto-P.I.T.E.R/"
languageCode: "pt-br"
title: "P.I.T.E.R - Buscadora de Investimentos em Inteligência Artificial"

# Configurações básicas
disableKinds: ["taxonomy", "term"]
enableRobotsTXT: true
