baseURL: "https://unb-mds.github.io/Projeto-B.I.I.A/"
languageCode: "pt-br"
title: "B.I.I.A - Buscadora de Investimentos em Inteligência Artificial"

# Configurações básicas
disableKinds: ["taxonomy", "term"]
enableRobotsTXT: true
