_merge: deep

# Site settings
title: "P.I.T.E.R - Procurador de Investimentos em Tecnologias na Educação Regional"
description: "Sistema inteligente para análise e busca de investimentos em Inteligência Artificial"
baseURL: "https://unb-mds.github.io/Projeto-P.I.T.E.R/"

# Design settings
design:
  header:
    sticky: true
    style: "light"
  footer:
    style: "dark"
  hero:
    style: "center"
    background: true
  colors:
    primary: "#6c757d"
    secondary: "#adb5bd"
    success: "#198754"
    danger: "#dc3545"
    warning: "#ffc107"
    info: "#0dcaf0"
    light: "#f8f9fa"
    dark: "#212529"
